try(library('alr3'))
try(library('boot'))
try(library('car'))
try(library('chron'))
try(library('cluster'))
try(library('clusterSim'))
try(library('clValid'))
try(library('DAAG'))
try(library('datasets'))
try(library('dtw'))
try(library('doSNOW'))
try(library('epicalc'))
try(library('faraway'))
try(library('fda'))
try(library('fdakma'))
try(library('foreach'))
try(library('foreign'))
try(library('fpc'))
try(library('gam'))
try(library('gdata'))
try(library('glmnet'))
try(library('gmodels'))
try(library('ggplot2'))
try(library('graphics'))
try(library('gridExtra'))
try(library('gtools'))
try(library('HiddenMarkov'))
try(library('HMM'))
try(library('Hmisc'))
try(library('hopach'))
try(library('inline'))
try(library('iterators'))
try(library('lattice'))
try(library('leaps'))
try(library('lme4'))
try(library('lmerTest'))
try(library('lmtest'))
try(library('longitudinalData'))
try(library('lpSolve'))
try(library('mAr'))
try(library('mclust'))
try(library('nlme'))
try(library('nortest'))
try(library('numDeriv'))
try(library('nws'))
try(library('orthogonalsplinebasis'))
try(library('plotrix'))
try(library('pls'))
try(library('plyr'))
try(library('profr'))
try(library('psych'))
try(library('quantmod'))
try(library('R2HTML'))
try(library('rbenchmark'))
try(library('reshape'))
try(library('robustX'))
try(library('sandwich'))
try(library('SenSrivastava'))
try(library('sos'))
try(library('stats'))
try(library('survey'))
try(library('survival'))
try(library('svMisc'))
try(library('tseries'))
#try(library('TTR'))
try(library('urca'))
try(library('vrtest'))
try(library('wle'))
try(library('xtable'))
try(library('xts'))
try(library('zipcode'))
try(library('zoo'))

try(library('seqinr'))

MyAutoLoads <- c('alr3', 
                 'boot', 
                 'car', 
                 'chron', 
                 'cluster', 
                 #'clusterSim', 
                 'clValid', 
                 'DAAG', 
                 'datasets', 
                 'dtw', 
                 'doSNOW', 
                 'epicalc', 
                 'faraway', 
                 'fda', 
                 'fdakma', 
                 'foreach', 
                 'foreign', 
                 'fpc', 
                 'gam', 
                 'gdata', 
                 'glmnet', 
                 'gmodels', 
                 'ggplot2', 
                 'graphics', 
                 'gridExtra', 
                 'gtools', 
                 'HiddenMarkov', 
                 'HMM', 
                 'Hmisc', 
                 #'hopach', 
                 'inline', 
                 'iterators', 
                 'lattice', 
                 'leaps',
                 'lmerTest',
                 'lmtest', 
                 #'longitudinalData', 
                 'lpSolve', 
                 'mAr', 
                 'mclust', 
                 'nlme', 
                 'nortest', 
                 'numDeriv', 
                 'nws', 
                 'PerformanceAnalytics', 
                 'plotrix', 
                 'pls', 
                 'plyr', 
                 'profr', 
                 'psych', 
                 'quantmod', 
                 'R2HTML', 
                 'rbenchmark', 
                 'reshape', 
                 'robustX', 
                 'sandwich', 
                 'SenSrivastava', 
                 'sos', 
                 'stats', 
                 'survey', 
                 'survival', 
                 'svMisc', 
                 'tseries', 
                 'urca', 
                 'vrtest', 
                 'wle', 
                 'xtable', 
                 'xts', 
                 'zipcode', 
                 'zoo', 
                 'seqinr'
)

