try(library('alr3'))
try(library('biganalytics'))
try(library('biglm'))
try(library('boot'))
try(library('car'))
try(library('chron'))
try(library('cluster'))
try(library('clusterSim'))
try(library('clValid'))
try(library('DAAG'))
try(library('datasets'))
try(library('doSNOW'))
try(library('epicalc'))
try(library('faraway'))
try(library('fBasics'))
try(library('fda'))
try(library('fdakma'))
try(library('foreach'))
try(library('fOptions'))
try(library('foreign'))
try(library('fpc'))
#try(library('fPortfolio'))
try(library('fRegression'))
try(library('gam'))
try(library('gdata'))
try(library('glmnet'))
try(library('gmodels'))
try(library('ggplot2'))
try(library('gplots'))
try(library('graphics'))
try(library('gridExtra'))
try(library('gtools'))
try(library('HiddenMarkov'))
try(library('HMM'))
try(library('Hmisc'))
try(library('inline'))
try(library('iterators'))
try(library('kernlab'))
try(library('knitr'))
try(library('lattice'))
try(library('leaps'))
try(library('limma'))
try(library('lme4'))
try(library('lmtest'))
try(library('lmtest'))
try(library('longitudinalData'))
try(library('mAr'))
try(library('Matrix'))
try(library('matrixStats'))
try(library('mclust'))
try(library('mgcv'))
try(library('nlme'))
try(library('nortest'))
try(library('numDeriv'))
try(library('nws'))
try(library('PerformanceAnalytics'))
try(library('plotrix'))
try(library('pls'))
try(library('plyr'))
try(library('profr'))
try(library('psych'))
try(library('quantmod'))
try(library('R2HTML'))
try(library('rbenchmark'))
try(library('Rcpp'))
try(library('reshape'))
try(library('reshape2'))
try(library('Rsymphony'))
try(library('sandwich'))
try(library('SenSrivastava'))
try(library('sets'))
try(library('sos'))
try(library('st'))
try(library('stats'))
try(library('survey'))
try(library('survival'))
try(library('svMisc'))
try(library('tseries'))
try(library('TTR'))
try(library('urca'))
try(library('vrtest'))
try(library('wle'))
try(library('wordcloud'))
## try(library('xlsReadWrite'))
## xls.getshlib()
try(library('XML'))
try(library('xtable'))
try(library('xts'))
try(library('zipcode'))
try(library('zoo'))

MyAutoLoads <- c('alr3', 'boot', 'car', 'chron', 'DAAG', 'datasets', 'doSNOW', 'epicalc', 'faraway', 
                 'foreach', 'gam', 'gdata', 'gmodels', 'ggplot2', 'gplots', 'graphics', 
                 'gtools', 'Hmisc', 'inline', 'iterators', 'lattice', 'leaps',  
                 'lmtest', 'lpSolve', 'mAr', 'nlme', 'nortest', 'nws', 'PerformanceAnalytics', 
                 'plotrix', 'pls', 'plyr', 'profr', 'quantmod', 'R2HTML', 'rbenchmark', 
                 'sandwich', 'SenSrivastava', 'sos', 'st', 'stats', 'survey', 'survival', 
                 'svMisc', 'tseries', 'TTR', 'urca', 'vrtest', 'wle', 'XML', 'xts', 'zoo')
