library('alr3')
library('biganalytics')
library('biglm')
library('boot')
library('car')
library('chron')
library('clusterSim')
library('DAAG')
library('datasets')
library('doSNOW')
library('epicalc')
library('faraway')
library('fBasics')
library('fda')
library('foreach')
library('fPortfolio')
library('fRegression')
library('gam')
library('gdata')
library('glmnet')
library('gmodels')
library('ggplot2')
library('gplots')
library('graphics')
library('gridExtra')
library('gtools')
try(library('HiddenMarkov'))
try(library('HMM'))
library('Hmisc')
library('inline')
library('iterators')
library('kernlab')
library('knitr')
library('lattice')
library('leaps')
library('limma')
library('lme4')
library('lmtest')
library('lpSolve')
library('mAr')
library('Matrix')
library('mclust')
library('mgcv')
library('nlme')
library('nortest')
library('nws')
library('PerformanceAnalytics')
library('plotrix')
library('pls')
library('plyr')
library('profr')
library('psych')
library('quantmod')
library('R2HTML')
library('rbenchmark')
library('Rcpp')
library('reshape')
library('Rsymphony')
library('sandwich')
library('SenSrivastava')
library('sos')
library('st')
library('stats')
library('survey')
library('survival')
library('svMisc')
library('tseries')
library('TTR')
library('urca')
library('vrtest')
library('wle')
library('wordcloud')
## library('xlsReadWrite')
## xls.getshlib()
library('XML')
library('xtable')
library('xts')
library('zipcode')
library('zoo')

MyAutoLoads <- c('alr3', 'boot', 'car', 'chron', 'DAAG', 'datasets', 'doSNOW', 'epicalc', 'faraway', 
                 'foreach', 'gam', 'gdata', 'gmodels', 'ggplot2', 'gplots', 'graphics', 
                 'gtools', 'Hmisc', 'inline', 'iterators', 'lattice', 'leaps',  
                 'lmtest', 'lpSolve', 'mAr', 'nlme', 'nortest', 'nws', 'PerformanceAnalytics', 
                 'plotrix', 'pls', 'plyr', 'profr', 'quantmod', 'R2HTML', 'rbenchmark', 
                 'sandwich', 'SenSrivastava', 'sos', 'st', 'stats', 'survey', 'survival', 
                 'svMisc', 'tseries', 'TTR', 'urca', 'vrtest', 'wle', 'XML', 'xts', 'zoo')
